{
    "nb_drones": 8,
    "connections": [
        {"connection": "start-maze_a1", "metadata": {"max_link_capacity": "2"}},
        {"connection": "maze_a1-maze_a2", "metadata": {}},
        {"connection": "maze_a1-maze_b1", "metadata": {}},
        {"connection": "maze_b1-maze_b2", "metadata": {}},
        {"connection": "maze_b2-maze_c2", "metadata": {}},
        {"connection": "maze_c2-maze_a2", "metadata": {}},
        {"connection": "maze_c2-bottleneck", "metadata": {}},
        {"connection": "start-dead_end1", "metadata": {"max_link_capacity": "2"}},
        {"connection": "dead_end1-dead_end2", "metadata": {}},
        {"connection": "maze_a2-dead_end3", "metadata": {}},
        {"connection": "maze_a2-trap_loop1", "metadata": {}},
        {"connection": "trap_loop1-trap_loop2", "metadata": {}},
        {"connection": "trap_loop2-maze_c1", "metadata": {}},
        {"connection": "maze_b1-maze_c1", "metadata": {}},
        {"connection": "maze_c1-maze_b2", "metadata": {}},
        {"connection": "maze_b2-maze_a2", "metadata": {}},
        {"connection": "bottleneck-final_stretch1", "metadata": {}},
        {"connection": "bottleneck-final_stretch2", "metadata": {}},
        {"connection": "bottleneck-final_stretch3", "metadata": {}},
        {"connection": "final_stretch1-goal", "metadata": {}},
        {"connection": "final_stretch2-goal", "metadata": {}},
        {"connection": "final_stretch3-goal", "metadata": {}},
    ],
    "start": {"coords": (0, 0), "metadata": {"color": "green", "max_drones": "8"}},
    "maze_a1": {"coords": (1, 0), "metadata": {"color": "blue", "max_drones": "2"}},
    "maze_a2": {"coords": (2, 0), "metadata": {"color": "blue"}},
    "maze_b1": {"coords": (1, 1), "metadata": {"color": "blue"}},
    "maze_b2": {"coords": (2, 1), "metadata": {"color": "blue", "max_drones": "2"}},
    "maze_c1": {"coords": (1, 2), "metadata": {"color": "blue"}},
    "maze_c2": {"coords": (3, 1), "metadata": {"color": "blue", "max_drones": "2"}},
    "dead_end1": {"coords": (0, 1), "metadata": {"color": "red", "max_drones": "2"}},
    "dead_end2": {"coords": (0, 2), "metadata": {"color": "red"}},
    "dead_end3": {"coords": (2, -1), "metadata": {"color": "red"}},
    "trap_loop1": {
        "coords": (4, 0),
        "metadata": {"zone": "restricted", "color": "orange"},
    },
    "trap_loop2": {
        "coords": (4, 2),
        "metadata": {"zone": "restricted", "color": "orange"},
    },
    "bottleneck": {
        "coords": (5, 1),
        "metadata": {"color": "yellow", "max_drones": "2"},
    },
    "final_stretch1": {
        "coords": (6, 0),
        "metadata": {"zone": "priority", "color": "cyan"},
    },
    "final_stretch2": {
        "coords": (6, 1),
        "metadata": {"zone": "priority", "color": "cyan"},
    },
    "final_stretch3": {
        "coords": (6, 2),
        "metadata": {"zone": "priority", "color": "cyan"},
    },
    "goal": {"coords": (7, 1), "metadata": {"color": "green", "max_drones": "8"}},
}
